default:
	g++ ./src/app.cpp -o ./out/app -Wall -Werror -pedantic
	./out/app < ./testcases/sample_1.in && echo "CORRECT_ANSWER: 2"
	./out/app < ./testcases/sample_2.in  && echo "CORRECT_ANSWER: 200000"
	./out/app < ./testcases/sample_3.in  && echo "CORRECT_ANSWER: 7"
	./out/app < ./testcases/sample_4.in  && echo "CORRECT_ANSWER: 2"
	./out/app < ./testcases/sample_5.in  && echo "CORRECT_ANSWER: 180008"