default:
	g++ ./src/app.cpp -o ./out/app -Wall -Werror -pedantic
	./out/app < ./tests/1.in && echo "Expected 7"
	./out/app < ./tests/2.in && echo "Expected 15"
	./out/app < ./tests/3.in && echo "Expected 31"