default:
	g++ ./src/app.cpp -o ./out/app -Wall -Werror -pedantic
	./out/app < ./tests/1.in && echo "YES\n9\nLDDRRRRRU"
	./out/app < ./tests/2.in && echo "NO"
	./out/app < ./tests/3.in && echo "YES" && echo "499998"